id: P009494
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1HU1
  title: དབྱངས་གསལ།
  author: ''
  volumes:
    04842352bd094d4b8e4c16250fb0a585:
      image_group_id: I2KG200905
      title: ''
      volume_number: 1
      total_pages: 16
      base_file: v001.txt
